name: GNN_AS
channels:
- rusty1s
- pytorch
- dglteam
- nvidia/label/cuda-12.4.0
- conda-forge
- defaults
dependencies:
- _openmp_mutex=4.5
- aiohappyeyeballs=2.4.4
- aiohttp=3.11.11
- aiosignal=1.3.2
- aom=3.9.1
- async-timeout=5.0.1
- attr=2.5.1
- attrs=24.3.0
- binutils=2.43
- binutils_impl_linux-64=2.43
- binutils_linux-64=2.43
- blas=1.0
- brotli-python=1.1.0
- bzip2=1.0.8
- c-compiler=1.7.0
- ca-certificates=2024.12.14
- cccl=2.3.2
- certifi=2024.12.14
- cffi=1.17.1
- charset-normalizer=3.4.1
- colorama=0.4.6
- cpython=3.10.16
- cuda-cccl=12.4.127
- cuda-cccl_linux-64=12.4.127
- cuda-command-line-tools=12.4.1
- cuda-compiler=12.4.1
- cuda-crt-dev_linux-64=12.4.131
- cuda-crt-tools=12.4.131
- cuda-cudart=12.4.127
- cuda-cudart-dev=12.4.127
- cuda-cudart-dev_linux-64=12.4.127
- cuda-cudart-static=12.4.127
- cuda-cudart-static_linux-64=12.4.127
- cuda-cudart_linux-64=12.4.127
- cuda-cuobjdump=12.4.127
- cuda-cupti=12.4.127
- cuda-cupti-dev=12.4.127
- cuda-cuxxfilt=12.4.127
- cuda-documentation=12.4.99
- cuda-driver-dev=12.4.127
- cuda-driver-dev_linux-64=12.4.127
- cuda-gdb=12.4.127
- cuda-nsight=12.4.127
- cuda-nvcc=12.4.131
- cuda-nvcc-dev_linux-64=12.4.131
- cuda-nvcc-impl=12.4.131
- cuda-nvcc-tools=12.4.131
- cuda-nvcc_linux-64=12.4.131
- cuda-nvdisasm=12.4.127
- cuda-nvml-dev=12.4.127
- cuda-nvprof=12.4.127
- cuda-nvprune=12.4.127
- cuda-nvrtc=12.4.127
- cuda-nvrtc-dev=12.4.127
- cuda-nvrtc-static=12.4.127
- cuda-nvtx=12.4.127
- cuda-nvvm-dev_linux-64=12.4.131
- cuda-nvvm-impl=12.4.131
- cuda-nvvm-tools=12.4.131
- cuda-nvvp=12.4.127
- cuda-opencl=12.4.127
- cuda-opencl-dev=12.4.127
- cuda-profiler-api=12.4.127
- cuda-runtime=12.4.1
- cuda-sanitizer-api=12.4.127
- cuda-toolkit=12.4.0
- cuda-tools=12.4.1
- cuda-version=12.4
- cuda-visual-tools=12.4.1
- cxx-compiler=1.7.0
- dataclasses=0.8
- dav1d=1.2.1
- dbus=1.13.6
- dgl=2.1.0
- expat=2.6.4
- filelock=3.16.1
- font-ttf-dejavu-sans-mono=2.37
- font-ttf-inconsolata=3.000
- font-ttf-source-code-pro=2.038
- font-ttf-ubuntu=0.83
- fontconfig=2.15.0
- fonts-conda-ecosystem=1
- fonts-conda-forge=1
- freetype=2.12.1
- frozenlist=1.5.0
- fsspec=2024.12.0
- fvcore=0.1.5.post20221221
- gcc=12.4.0
- gcc_impl_linux-64=12.4.0
- gcc_linux-64=12.4.0
- gds-tools=1.9.1.3
- gmp=6.3.0
- gmpy2=2.1.5
- gxx=12.4.0
- gxx_impl_linux-64=12.4.0
- gxx_linux-64=12.4.0
- h2=4.1.0
- hpack=4.0.0
- hyperframe=6.0.1
- idna=3.10
- intel-openmp=2022.0.1
- iopath=0.1.10
- jinja2=3.1.5
- kernel-headers_linux-64=3.10.0
- keyutils=1.6.1
- krb5=1.21.3
- lcms2=2.16
- ld_impl_linux-64=2.43
- lerc=4.0.0
- llvm-openmp=19.1.7
- lz4-c=1.10.0
- markupsafe=3.0.2
- mkl=2023.2.0
- mpc=1.3.1
- mpfr=4.2.1
- mpmath=1.3.0
- multidict=6.1.0
- ncurses=6.5
- networkx=3.4.2
- nsight-compute=2024.1.1.4
- nspr=4.36
- nss=3.107
- ocl-icd=2.3.2
- opencl-headers=2024.10.24
- openssl=3.4.0
- pcre2=10.44
- pip=24.3.1
- portalocker=3.0.0
- propcache=0.2.1
- psutil=6.1.1
- pthread-stubs=0.4
- pycparser=2.22
- pyparsing=3.2.1
- pysocks=1.7.1
- python=3.10.16
- python_abi=3.10
- pytorch-cuda=12.4
- pytorch-geometric=2.6.1
- pytorch-mutex=1.0
- pytorch3d=0.7.7
- pyyaml=6.0.2
- rav1e=0.6.6
- rdma-core=55.0
- readline=8.2
- requests=2.32.3
- setuptools=75.8.0
- sleef=3.7
- svt-av1=2.3.0
- sysroot_linux-64=2.17
- tabulate=0.9.0
- tbb=2021.13.0
- termcolor=2.5.0
- tk=8.6.13
- torchtriton=3.1.0
- tqdm=4.67.1
- typing-extensions=4.12.2
- typing_extensions=4.12.2
- wayland=1.23.1
- wheel=0.45.1
- x265=3.5
- xkeyboard-config=2.42
- yacs=0.1.8
- yaml=0.2.5
- yarl=1.18.3
- zstandard=0.23.0
- zstd=1.5.6
